@BASE_URL=http://localhost:3000

### Register
POST {{BASE_URL}}/api/auth/register
Content-Type: application/json

   
    {
    "name" : "prame4",
    "email" : "prame4@gmail.com",
    "password" : "123456",
    "confirmPassword" : "123456"
}
   

### log in
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{   
    "email" : "prame135@gmail.com",
    "password" : "123456"
}
### get
GET {{BASE_URL}}/api/auth/me
Content-Type: application/json
Authorization: :Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQyYmEzMGVjLWNhNWYtNDkyMy1iNWE5LTRhZDQ2YzVjZjVmYiIsImVtYWlsIjoicHJhbWUxMzVAZ21haWwuY29tIiwibmFtZSI6InByYW1lMiIsImF2YXRhclVybCI6bnVsbCwicm9sZSI6IlVTRVIiLCJwcm92aWRlciI6IkxPQ0FMIiwiZ29vZ2xlSWQiOm51bGwsImlhdCI6MTc3NTcxODA1MywiZXhwIjoxNzc3MTg2ODUzfQ.l9DKA50hi9cGVLA5WerUCpBXUjfMPuueMPZP2FRh4QU